-- MySQL Script generated by MySQL Workbench
-- Tue Jan  4 19:11:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookstore` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bookstore` ;

-- -----------------------------------------------------
-- Table `bookstore`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`user` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`user` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Gender` VARCHAR(255) NULL DEFAULT NULL,
  `Avatar` VARCHAR(255) NULL DEFAULT NULL,
  `Phone` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bookstore`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`account` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`account` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `Username` VARCHAR(255) NULL DEFAULT NULL,
  `Password` VARCHAR(255) NULL DEFAULT NULL,
  `Role` TINYINT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  INDEX `FKAccount182293` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FKAccount182293`
    FOREIGN KEY (`UserID`)
    REFERENCES `bookstore`.`user` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bookstore`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`address` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`address` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `City` VARCHAR(255) NULL DEFAULT NULL,
  `District` VARCHAR(255) NULL DEFAULT NULL,
  `addressDetail` VARCHAR(255) NULL DEFAULT NULL,
  `shipmentCityId` VARCHAR(10) NULL DEFAULT NULL,
  `shipmentDistrictId` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FKAddress555440` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FKAddress555440`
    FOREIGN KEY (`UserID`)
    REFERENCES `bookstore`.`user` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bookstore`.`author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`author` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`author` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL DEFAULT NULL,
  `Biography` VARCHAR(255) NULL DEFAULT NULL,
  `Email` VARCHAR(255) NULL DEFAULT NULL,
  `Address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bookstore`.`bookitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`bookitem` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`bookitem` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Price` FLOAT NOT NULL,
  `Discount` FLOAT NOT NULL DEFAULT '0',
  `SellingStatus` INT NULL DEFAULT '0',
  `Description` LONGTEXT NULL DEFAULT NULL,
  `Image` VARCHAR(255) NULL DEFAULT NULL,
  `Name` MEDIUMTEXT NULL DEFAULT NULL,
  `Category` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bookstore`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`book` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`book` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `BookItemID` INT NOT NULL,
  `IBSN` VARCHAR(255) NULL DEFAULT NULL,
  `Tittle` MEDIUMTEXT NULL DEFAULT NULL,
  `Sumary` LONGTEXT NULL DEFAULT NULL,
  `PublicationYear` VARCHAR(255) NULL DEFAULT NULL,
  `NumberOfPage` INT NOT NULL,
  `Cost` FLOAT NOT NULL,
  `Language` VARCHAR(255) NULL DEFAULT NULL,
  `RemainingQuantity` INT NOT NULL,
  `Status` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FKBook313834` (`BookItemID` ASC) VISIBLE,
  CONSTRAINT `FKBook313834`
    FOREIGN KEY (`BookItemID`)
    REFERENCES `bookstore`.`bookitem` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bookstore`.`bookauthor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`bookauthor` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`bookauthor` (
  `BookID` INT NOT NULL,
  `AuthorID` INT NOT NULL,
  PRIMARY KEY (`BookID`, `AuthorID`),
  INDEX `FKBookAuthor144512` (`AuthorID` ASC) VISIBLE,
  CONSTRAINT `FKBookAuthor126018`
    FOREIGN KEY (`BookID`)
    REFERENCES `bookstore`.`book` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `FKBookAuthor144512`
    FOREIGN KEY (`AuthorID`)
    REFERENCES `bookstore`.`author` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bookstore`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`cart` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`cart` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `TotalPrice` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FKCart424327` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FKCart424327`
    FOREIGN KEY (`UserID`)
    REFERENCES `bookstore`.`user` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bookstore`.`cartitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`cartitem` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`cartitem` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Quantity` INT NOT NULL,
  `BookItemID` INT NOT NULL,
  `CartID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `CartItem` (`BookItemID` ASC) VISIBLE,
  INDEX `CartItem2` (`CartID` ASC) VISIBLE,
  CONSTRAINT `CartItem`
    FOREIGN KEY (`BookItemID`)
    REFERENCES `bookstore`.`bookitem` (`ID`),
  CONSTRAINT `CartItem2`
    FOREIGN KEY (`CartID`)
    REFERENCES `bookstore`.`cart` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bookstore`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`customer` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`customer` (
  `UserID` INT NOT NULL,
  PRIMARY KEY (`UserID`),
  CONSTRAINT `FKCustomer697196`
    FOREIGN KEY (`UserID`)
    REFERENCES `bookstore`.`user` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bookstore`.`fullname`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`fullname` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`fullname` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `FirstName` VARCHAR(255) NULL DEFAULT NULL,
  `MidName` VARCHAR(255) NULL DEFAULT NULL,
  `LastName` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FKFullName19388` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FKFullName19388`
    FOREIGN KEY (`UserID`)
    REFERENCES `bookstore`.`user` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bookstore`.`shipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`shipment` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`shipment` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(255) NULL DEFAULT NULL,
  `Cost` FLOAT NOT NULL,
  `ShipUnit` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bookstore`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`payment` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`payment` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Status` INT NULL DEFAULT NULL,
  `Amount` FLOAT NOT NULL,
  `Type` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bookstore`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`order` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`order` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CustomerUserID` INT NOT NULL,
  `ShipmentID` INT NOT NULL,
  `CreatedDate` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `Status` INT NULL DEFAULT '0',
  `PaymentID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FKOrder751924` (`ShipmentID` ASC) VISIBLE,
  INDEX `FKOrder321061_idx` (`CustomerUserID` ASC) VISIBLE,
  INDEX `FKOrder92191` (`PaymentID` ASC) VISIBLE,
  CONSTRAINT `FKOrder321061`
    FOREIGN KEY (`CustomerUserID`)
    REFERENCES `bookstore`.`user` (`ID`),
  CONSTRAINT `FKOrder751924`
    FOREIGN KEY (`ShipmentID`)
    REFERENCES `bookstore`.`shipment` (`ID`),
  CONSTRAINT `FKOrder92191`
    FOREIGN KEY (`PaymentID`)
    REFERENCES `bookstore`.`payment` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bookstore`.`orderitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`orderitem` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`orderitem` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Quantity` INT NULL DEFAULT NULL,
  `BookItemID` INT NULL DEFAULT NULL,
  `OrderID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `OrderItem2` (`OrderID` ASC) VISIBLE,
  INDEX `OrderItem` (`BookItemID` ASC) VISIBLE,
  CONSTRAINT `OrderItem`
    FOREIGN KEY (`BookItemID`)
    REFERENCES `bookstore`.`bookitem` (`ID`),
  CONSTRAINT `OrderItem2`
    FOREIGN KEY (`OrderID`)
    REFERENCES `bookstore`.`order` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bookstore`.`publisher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`publisher` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`publisher` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `BookID` INT NOT NULL,
  `Name` VARCHAR(255) NULL DEFAULT NULL,
  `Address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FKPublisher931365` (`BookID` ASC) VISIBLE,
  CONSTRAINT `FKPublisher931365`
    FOREIGN KEY (`BookID`)
    REFERENCES `bookstore`.`book` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bookstore`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`staff` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`staff` (
  `Salary` FLOAT NOT NULL,
  `UserID` INT NOT NULL,
  PRIMARY KEY (`UserID`),
  CONSTRAINT `FKStaff312633`
    FOREIGN KEY (`UserID`)
    REFERENCES `bookstore`.`user` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
