# Generated by Django 4.0.4 on 2022-05-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_remove_order_address_remove_order_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
