# Generated by Django 4.0.4 on 2022-05-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_order_order_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_code',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='content',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='username',
        ),
        migrations.AddField(
            model_name='order',
            name='content',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
