# Generated by Django 4.0.4 on 2022-05-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_rename_order_code_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
