# Generated by Django 4.0.4 on 2022-05-15 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_order_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
