# Generated by Django 4.0.4 on 2022-05-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_remove_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='code',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
