# Generated by Django 4.0.4 on 2022-05-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_orderitem_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='Order',
        ),
    ]
