# Generated by Django 4.0.4 on 2022-05-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0014_remove_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
